name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, & Scan
    runs-on: self-hosted  # Adjust for your runner environment

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Retrieve full history for better analysis

      - name: Build Docker image
        run: |
          docker build -t tic-tac-toe .

      - name: Tag Docker image (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' }}
        run: |
          docker tag tic-tac-toe ${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe:latest

      - name: Login to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
