name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Login step (only for non-dependabot pushes)
      - name: Login to DockerHub (except dependabot)
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag image
        run: |
          docker build -t webcow-app .
          docker tag webcow-app naresh3451234/webcow-app:latest

      - name: Push to registry (consider private registry)
        run: |
          docker push naresh3451234/webcow-app:latest

  # Add additional jobs for analysis and scanning here
