on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: [self-hosted]
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t naresh3451213/wisecow-app:latest .
          docker push naresh3451213/wisecow-app:latest
          



  deploy:  # Consider a separate job for deployment
    name: Deploy to Kubernetes
    runs-on: [self-hosted]
    needs: build  # Or analyze if included
    steps:
      - name: Pull Deployment Image
        run: docker pull naresh3451213/wisecow-app:latest
        
      - name: Deploy to container
        run: docker run -d --name wisecow -p 4000:4000 naresh3451213/wisecow-app:latest

      - name: Update kubeconfig
        run: aws eks --region us-west-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to kubernetes
        run: kubectl apply -f wisecow-deployment.yaml
        
       
  

   

 
