name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Retrieve full codebase for analysis

      - name: Build and tag image
        run: |
          docker build -t webcow-app .
          docker tag webcow-app naresh3451213/webcow-app:latest

      - name: Push to registry (consider private registry for production)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push naresh3451213/webcow-app:latest

  # Add additional jobs for analysis and scanning here
  # These jobs can use tools like Trivy, Snyk, or Clair in Docker containers
