on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: [self-hosted]
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t naresh3451213/wisecow-app:latest .
          docker push naresh3451213/wisecow-app:latest



 
