on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t naresh3451213/tic:latest .
          docker push naresh3451213/tic:latest

  analyze:
    name: Analyze Image (Optional)
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Pull Image for Analysis
        run: docker pull naresh3451213/tic:latest

      - name: Run Trivy Scan (Example)
        run: trivy image naresh3451213/tic:latest  # Save output to a file for further processing

  deploy:  # Consider a separate job for deployment
    name: Deploy to Kubernetes
    runs-on: [self-hosted]
    needs: build  # Or analyze if included
    steps:
      - name: Pull Deployment Image
        run: docker pull sevenajay/tic-tac-toe:latest

      - name: Update Kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yml
